workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && pod install --verbose && cd ..
      - flutter build ios --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods
