workflows:
  android-release:
    name: Android Release Build
    environment:
      vars:
        JAVA_VERSION: 17
      groups:
        - signing_credentials # Asegura que el grupo de variables de firma está activado
      flutter: stable
    scripts:
      - name: Decodificar Keystore desde Base64
        script: |
          echo $CM_KEYSTORE | base64 --decode > /Users/builder/clone/android/petcare.jks

      - name: Limpiar y actualizar dependencias
        script: |
          flutter clean
          flutter pub get

      - name: Compilar APK en modo release
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache

  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      FLUTTER_ROOT: /opt/flutter
    scripts:
      - name: Instalando Flutter
        script: |
          git clone https://github.com/flutter/flutter.git -b stable /opt/flutter
          export PATH="$PATH:/opt/flutter/bin"
          flutter --version
          flutter doctor -v

      - name: Limpiando y actualizando dependencias
        script: |
          flutter clean
          flutter pub upgrade --major-versions
          flutter pub get

      - name: Instalando CocoaPods
        script: |
          gem install cocoapods -v 1.16.2
          pod repo update
          pod cache clean --all

      - name: Eliminando Pods antiguos y reinstalando
        script: |
          rm -rf ios/Pods ios/.symlinks ios/Flutter/Flutter.framework ios/Flutter/Flutter.podspec ios/Podfile.lock
          cd ios && pod install --verbose && cd ..

      - name: Compilando aplicación para iOS
        script: |
          flutter build ios --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods

