flutter_root = ENV['FLUTTER_ROOT'] || File.expand_path('..', __dir__)
load File.join(flutter_root, 'packages/flutter_tools/bin/podhelper.rb')

platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  install_all_flutter_pods(flutter_root)
end

